version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-teste-dev
    container_name: laravel-teste-dev
    volumes:
      - .:/var/www
    networks:
      - teste-dev-network

  webserver:
    image: nginx:alpine
    container_name: nginx-teste-dev
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - teste-dev-network

  mysql:
    image: mysql:8.0
    container_name: mysql-teste-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - teste-dev-network

networks:
  teste-dev-network:
    driver: bridge

volumes:
  mysql_data:
